apiVersion: v2
name: parksmap
version: 1.0.0
appVersion: "1.0.0"
description: Helm chart para el despliegue de Parksmap App en OpenShift GitOps Workshop
type: application
keywords:
  - parksmap
  - nationalparks
  - openshift
  - demo
  - gitops
home: https://github.com/workshop-gitops/cap12-labs
sources:
  - https://github.com/workshop-gitops/cap12-labs
maintainers:
  - name: Workshop Team
    email: workshop@example.com
icon: https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg
annotations:
  category: DemoApplication
