# ============================================
# Values para Staging (STAGING)
# ============================================
# 2 réplicas, recursos medios, tags semver fijos

frontend:
  replicaCount: 2
  image:
    repository: quay.io/openshiftroadshow/parksmap
    tag: "v1.2.0"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  config:
    appName: "National Parks Explorer - STAGING"
    logLevel: "info"

backend:
  replicaCount: 2
  image:
    repository: quay.io/openshiftroadshow/nationalparks-py
    tag: "v1.1.0"
  resources:
    limits:
      cpu: 600m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

mongodb:
  replicaCount: 1
  image:
    repository: quay.io/centos7/mongodb-36-centos7
    tag: "v3.6"
  resources:
    limits:
      cpu: 600m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: true
    size: 2Gi

autoscaling:
  enabled: false
