{{- if and .Values.backend.enabled .Values.backend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "parksmap.fullname" . }}-backend
  labels:
    {{- include "parksmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: nationalparks
    app.kubernetes.io/role: backend
    type: parksmap-backend
spec:
  port:
    targetPort: http
  {{- if .Values.backend.route.tls.enabled }}
  tls:
    termination: {{ .Values.backend.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.backend.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "parksmap.fullname" . }}-backend
    weight: 100
  wildcardPolicy: None
  {{- if .Values.backend.route.host }}
  host: {{ .Values.backend.route.host }}
  {{- end }}
{{- end }}
