{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parksmap.fullname" . }}-frontend
  labels:
    {{- include "parksmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: parksmap
    app.kubernetes.io/role: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "parksmap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: parksmap
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
{{- end }}
