{{- if and .Values.frontend.enabled .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "parksmap.fullname" . }}-frontend
  labels:
    {{- include "parksmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: parksmap
    app.kubernetes.io/role: frontend
spec:
  port:
    targetPort: http
  {{- if .Values.frontend.route.tls.enabled }}
  tls:
    termination: {{ .Values.frontend.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.frontend.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "parksmap.fullname" . }}-frontend
    weight: 100
  wildcardPolicy: None
  {{- if .Values.frontend.route.host }}
  host: {{ .Values.frontend.route.host }}
  {{- end }}
{{- end }}
