{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parksmap.fullname" . }}-mongodb
  labels:
    {{- include "parksmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/role: database
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      {{- include "parksmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "parksmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/role: database
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongodb.service.targetPort }}
          name: mongodb
          protocol: TCP
        env:
        - name: MONGODB_USER
          value: {{ .Values.mongodb.env.mongodbUser | quote }}
        - name: MONGODB_PASSWORD
          value: {{ .Values.mongodb.env.mongodbPassword | quote }}
        - name: MONGODB_DATABASE
          value: {{ .Values.mongodb.env.mongodbDatabase | quote }}
        - name: MONGODB_ADMIN_PASSWORD
          value: {{ .Values.mongodb.env.mongodbAdminPassword | quote }}
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 10 }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
      volumes:
      - name: mongodb-data
        {{- if .Values.mongodb.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "parksmap.fullname" . }}-mongodb-data
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
