{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "parksmap.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_SERVICE_NAME: {{ .Values.secrets.data.DATABASE_SERVICE_NAME | quote }}
  MONGODB_DATABASE: {{ .Values.secrets.data.MONGODB_DATABASE | quote }}
  MONGODB_USER: {{ .Values.secrets.data.MONGODB_USER | quote }}
  MONGODB_PASSWORD: {{ .Values.secrets.data.MONGODB_PASSWORD | quote }}
  MONGODB_ADMIN_PASSWORD: {{ .Values.secrets.data.MONGODB_ADMIN_PASSWORD | quote }}
{{- end }}
